version: '3.8'

services:
  chimpgpt:
    build: .
    container_name: chimpgpt
    restart: unless-stopped
    ports:
      - '${STATUS_PORT:-3000}:3000'
    volumes:
      - ./data:/usr/src/app/data
      - ./.env:/usr/src/app/.env:ro
    environment:
      - NODE_ENV=production
      - TZ=UTC
    healthcheck:
      test: ['CMD', 'wget', '-q', '--spider', 'http://localhost:3000/health']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s
